pub mod ext;
pub mod hooks;
pub mod keys;
pub mod layout;
pub mod measure;
pub mod node;
pub mod style;
pub mod view;

pub use reactatui_macros::{
    bind, children, component, key_pattern as __key_pattern, lambda, layout, style, tui,
};

pub use ext::FrameExt;
pub use layout::{FlexItemNode, FlexNode, GridItemNode, GridNode, Padding};
pub type Flex<'a> = FlexNode<'a>;
pub type Grid<'a> = GridNode<'a>;
pub use hooks::{EventOutcome, RedrawHandle, Runtime};
pub use node::{StateHandle, TuiNode};
pub use style::CombinedStyle;
pub use style::ReactatuiStyle;
pub use view::{AnyView, View, WidgetView, view};

/// Child nodes supplied to a component's `#[slot]` parameters.
///
/// This type is constructed by `tui!` and consumed by code generated by
/// `#[component]`; component authors normally only interact with `TuiNode`.
#[doc(hidden)]
pub struct Slot<'a> {
    children: Vec<TuiNode<'a>>,
}

/// Bindings supplied to a component's `#[bind]` parameters.
///
/// Constructed by `tui!` and consumed by code generated by `#[component]`.
#[doc(hidden)]
pub struct Bindings {
    values: Vec<(Option<&'static str>, Box<dyn std::any::Any>)>,
}

impl Bindings {
    #[doc(hidden)]
    pub fn new(values: Vec<(Option<&'static str>, Box<dyn std::any::Any>)>) -> Self {
        let mut names = std::collections::HashSet::new();
        for (name, _) in &values {
            if !names.insert(*name) {
                let label = name.unwrap_or("default");
                panic!("binding `{label}` was provided more than once");
            }
        }
        Self { values }
    }

    #[doc(hidden)]
    pub fn take<T: 'static>(&mut self, name: Option<&str>) -> Option<T> {
        let index = self
            .values
            .iter()
            .position(|(candidate, _)| *candidate == name)?;
        let (_, value) = self.values.remove(index);
        Some(*value.downcast::<T>().unwrap_or_else(|_| {
            let label = name.unwrap_or("default");
            panic!("binding `{label}` has an incompatible state type")
        }))
    }

    #[doc(hidden)]
    pub fn assert_empty(&self) {
        if let Some((name, _)) = self.values.first() {
            let label = name.unwrap_or("default");
            panic!("binding `{label}` is not accepted by this component");
        }
    }
}

impl<'a> Slot<'a> {
    #[doc(hidden)]
    pub fn new(children: Vec<TuiNode<'a>>) -> Self {
        Self { children }
    }

    #[doc(hidden)]
    pub fn take(&mut self, name: Option<&str>) -> Option<TuiNode<'a>> {
        let matched = self.drain(name);
        (!matched.is_empty()).then(|| TuiNode::opaque_fragment(matched))
    }

    #[doc(hidden)]
    pub fn take_all(&mut self, name: Option<&str>) -> Vec<TuiNode<'a>> {
        self.drain(name)
    }

    fn drain(&mut self, name: Option<&str>) -> Vec<TuiNode<'a>> {
        let mut matched = Vec::new();
        let mut unmatched = Vec::new();

        for child in self.children.drain(..) {
            match child {
                TuiNode::Slotted(node, slot_name) if name == Some(slot_name.as_str()) => {
                    matched.push(*node);
                }
                child @ TuiNode::Slotted(_, _) => unmatched.push(child),
                child if name.is_none() => matched.push(child),
                child => unmatched.push(child),
            }
        }
        self.children = unmatched;
        matched
    }
}

pub mod prelude {
    pub use crate::hooks::{
        Action, Callback, FocusHandle, KeyHandle, Memo, Propagation, Resource, State, Stored, bind,
        effect, focus, keys, memo, resource, resource_or, state, stored,
    };
    // layout::Style/Align/Justify/FlexBasis stay out of the prelude glob —
    // this module already re-exports ratatui::style::Style below, and
    // colliding those two under one glob import would be a footgun.
    // ReactatuiStyle and the `style!` macro are safe to include: neither
    // name collides with anything else here.
    pub use crate::{
        AnyView, Bindings, CombinedStyle, EventOutcome, Flex, FlexItemNode, FlexNode, FrameExt,
        Grid, GridItemNode, GridNode, Padding, ReactatuiStyle, RedrawHandle, Runtime, StateHandle,
        TuiNode, WidgetView, bind, children, component, lambda, layout, style, tui, view,
    };
    pub use ratatui::{
        layout::{Alignment, Constraint, Direction, Layout, Rect},
        style::{Color, Modifier, Style},
    };
}
