pub mod ext;
pub mod hooks;
pub mod keys;
pub mod layout;
pub mod measure;
pub mod node;
pub mod style;
pub mod view;

pub use reactatui_macros::{children, component, key_pattern as __key_pattern, layout, tui};

pub use ext::FrameExt;
pub use layout::{FlexItemNode, FlexNode, GridItemNode, GridNode, Padding};
pub type Flex<'a> = FlexNode<'a>;
pub type Grid<'a> = GridNode<'a>;
pub use hooks::{EventOutcome, RedrawHandle, Runtime};
pub use node::{StateHandle, TuiNode};
pub use style::CombinedStyle;
pub use view::{AnyView, View, WidgetView, view};

/// Child nodes supplied to a component's `#[slot]` parameters.
///
/// This type is constructed by `tui!` and consumed by code generated by
/// `#[component]`; component authors normally only interact with `TuiNode`.
#[doc(hidden)]
pub struct Slot<'a> {
    children: Vec<TuiNode<'a>>,
}

impl<'a> Slot<'a> {
    #[doc(hidden)]
    pub fn new(children: Vec<TuiNode<'a>>) -> Self {
        Self { children }
    }

    #[doc(hidden)]
    pub fn take(&mut self, name: Option<&str>) -> Option<TuiNode<'a>> {
        let matched = self.drain(name);
        (!matched.is_empty()).then(|| TuiNode::opaque_fragment(matched))
    }

    #[doc(hidden)]
    pub fn take_all(&mut self, name: Option<&str>) -> Vec<TuiNode<'a>> {
        self.drain(name)
    }

    fn drain(&mut self, name: Option<&str>) -> Vec<TuiNode<'a>> {
        let mut matched = Vec::new();
        let mut unmatched = Vec::new();

        for child in self.children.drain(..) {
            match child {
                TuiNode::Slotted(node, slot_name) if name == Some(slot_name.as_str()) => {
                    matched.push(*node);
                }
                child @ TuiNode::Slotted(_, _) => unmatched.push(child),
                child if name.is_none() => matched.push(child),
                child => unmatched.push(child),
            }
        }
        self.children = unmatched;
        matched
    }
}

pub mod prelude {
    pub use crate::hooks::{
        Action, Callback, FocusHandle, KeyHandle, Memo, Propagation, Resource, State, Stored,
        resource, state, try_resource, use_effect, use_focus, use_key, use_memo, use_ref,
        use_state,
    };
    // layout::Style/Align/Justify/FlexBasis stay out of the prelude glob —
    // this module already re-exports ratatui::style::Style below, and
    // colliding those two under one glob import would be a footgun.
    // CombinedStyle and the `style!` macro are safe to include: neither
    // name collides with anything else here.
    pub use crate::{
        AnyView, CombinedStyle, EventOutcome, Flex, FlexItemNode, FlexNode, FrameExt, Grid,
        GridItemNode, GridNode, Padding, RedrawHandle, Runtime, StateHandle, TuiNode, WidgetView,
        children, component, layout, style, tui, view,
    };
    pub use ratatui::{
        layout::{Alignment, Constraint, Direction, Layout, Rect},
        style::{Color, Modifier, Style},
    };
}
