use std::{env, fs, path::PathBuf, process::ExitCode};

use typify::{TypeSpace, TypeSpaceSettings};

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("{error}");
            ExitCode::FAILURE
        }
    }
}

fn run() -> Result<(), Box<dyn std::error::Error>> {
    let check = env::args().skip(1).any(|arg| arg == "--check");
    let crate_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("codegen crate must be nested under lazydbg-dap")
        .to_owned();
    let schema_path = crate_dir.join("debug-adapter-protocol/debugAdapterProtocol.json");
    let output_path = crate_dir.join("src/generated.rs");

    let mut schema_json =
        serde_json::from_str::<serde_json::Value>(&fs::read_to_string(&schema_path)?)?;
    verify_dispatch_coverage(&crate_dir, &schema_json)?;
    make_protocol_objects_open(&mut schema_json);
    allow_zero_sequence_numbers(&mut schema_json);
    let schema = serde_json::from_value::<schemars::schema::RootSchema>(schema_json)?;
    let mut settings = TypeSpaceSettings::default();
    settings
        .with_struct_builder(false)
        .with_derive("PartialEq".to_owned());
    let mut types = TypeSpace::new(&settings);
    types.add_root_schema(schema)?;

    let tokens = types.to_stream();
    let syntax = syn::parse2::<syn::File>(tokens)?;
    let generated = format!(
        "// @generated by lazydbg-dap-codegen. Do not edit manually.\n\n{}",
        prettyplease::unparse(&syntax)
    );

    if check {
        let existing = fs::read_to_string(&output_path)?;
        if existing != generated {
            return Err(format!(
                "{} is stale; run `cargo run -p lazydbg-dap-codegen`",
                output_path.display()
            )
            .into());
        }
    } else {
        fs::write(output_path, generated)?;
    }
    Ok(())
}

fn allow_zero_sequence_numbers(schema: &mut serde_json::Value) {
    // lldb-dap uses zero for response sequence numbers, despite DAP's stated
    // minimum of one. Keep the wire model interoperable with real adapters.
    schema["definitions"]["ProtocolMessage"]["properties"]["seq"]["minimum"] =
        serde_json::Value::from(0);
}

fn make_protocol_objects_open(value: &mut serde_json::Value) {
    match value {
        serde_json::Value::Array(values) => {
            for value in values {
                make_protocol_objects_open(value);
            }
        }
        serde_json::Value::Object(object) => {
            let is_protocol_object = object.get("type").and_then(|value| value.as_str())
                == Some("object")
                && object.contains_key("properties");
            if is_protocol_object {
                object
                    .entry("additionalProperties")
                    .or_insert(serde_json::Value::Bool(true));
            }
            for value in object.values_mut() {
                make_protocol_objects_open(value);
            }
        }
        _ => {}
    }
}

fn verify_dispatch_coverage(
    crate_dir: &std::path::Path,
    schema: &serde_json::Value,
) -> Result<(), Box<dyn std::error::Error>> {
    let request_source = fs::read_to_string(crate_dir.join("src/request.rs"))?;
    let protocol_source = fs::read_to_string(crate_dir.join("src/protocol.rs"))?;
    let definitions = schema["definitions"]
        .as_object()
        .ok_or("schema has no definitions object")?;

    for (name, definition) in definitions {
        if name == "Request" || !name.ends_with("Request") {
            continue;
        }
        let Some(command) = literal_property(definition, "command") else {
            continue;
        };
        if !request_source.contains(&format!("\"{command}\"")) {
            return Err(format!("request {command:?} has no DapRequest implementation").into());
        }
    }
    for (name, definition) in definitions {
        if name == "Event" || !name.ends_with("Event") {
            continue;
        }
        let Some(event) = literal_property(definition, "event") else {
            continue;
        };
        if !protocol_source.contains(&format!("\"{event}\" =>")) {
            return Err(format!("event {event:?} has no typed dispatch variant").into());
        }
    }
    Ok(())
}

fn literal_property<'a>(definition: &'a serde_json::Value, property: &str) -> Option<&'a str> {
    definition["allOf"]
        .as_array()?
        .iter()
        .find_map(|part| part["properties"][property]["enum"][0].as_str())
}
